# Introduction to NumPy Library

In [1]:
import numpy as np

## Arrays

### 0D Arrays

In [ ]:
arr = np.array(42)
print(type(arr))

### 1D Arrays

In [ ]:
arr = np.array([1,2,3,4])
arr[0] = 100
print(arr)
print(arr.shape)

### 2D Arrays

In [ ]:
arr = np.array(
    [
        [1,2,3],
        [2,3,4]
    ]
)

print(arr)
print(type(arr))

print(arr.shape)
print(arr.size)

### 3D Arrays

In [ ]:
d234 = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8]
        ],
        [
            [11, 22, 33, 44],
            [55, 66, 77, 88]
        ]
    ]
)

print(d234.ndim)

## Vector Operations

### Vector Operations

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + 3)
print(a ** 2)
print(a + b)
print(a * b)
print(a - b)

[4 5 6 7]
[ 1  4  9 16]
[ 6  8 10 12]
[ 5 12 21 32]
[-4 -4 -4 -4]


### Dot, Matrix and Vector Product Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])

print(a.dot(b)) # dot (scalar) product
print(np.cross(a, b)) # cross (vector) product

V = np.array([0, 1, 2])
M = np.array(
    [[0, 1, 2],
    [3,4,5],
    [6,7,8]]
)

print(V @ M) # Matrix multiplication